/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./web/index.html", "./web/src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#faf8ff",
        primary: "#001629",
        "on-primary": "#ffffff",
        "primary-container": "#002b49",
        "on-primary-container": "#7293b6",
        "primary-fixed": "#cfe5ff",
        "primary-fixed-dim": "#a8caef",
        "on-primary-fixed": "#001d34",
        "on-primary-fixed-variant": "#274969",
        secondary: "#4059aa",
        "on-secondary": "#ffffff",
        "secondary-container": "#8fa7fe",
        "on-secondary-container": "#1d3989",
        "secondary-fixed": "#dce1ff",
        "secondary-fixed-dim": "#b6c4ff",
        tertiary: "#260e00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#441f01",
        "on-tertiary-container": "#bd835b",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-fixed-dim": "#fab98d",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#faf8ff",
        "on-background": "#131b2e",
        surface: "#faf8ff",
        "surface-bright": "#faf8ff",
        "surface-tint": "#406182",
        "on-surface": "#131b2e",
        "on-surface-variant": "#42474d",
        "surface-variant": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        outline: "#73777e",
        "outline-variant": "#c3c7ce",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#a8caef",
        success: "#1f7a3d",
        "success-container": "#c8f0d4",
        brand: {
          50: "#eef1ff", 100: "#dce1ff", 200: "#b6c4ff", 300: "#8fa7fe", 400: "#6b82e0",
          500: "#4059aa", 600: "#274991", 700: "#1d3989", 800: "#002b49", 900: "#001629",
        },
      },
      fontFamily: {
        sans: ["Inter", "Noto Sans KR", "system-ui", "sans-serif"],
        headline: ["Hanken Grotesk", "Noto Sans KR", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        none: "0",
        DEFAULT: "0.125rem",
        sm: "0.0625rem",
        md: "0.1875rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
